### ISSUE TITLE
Merge data download scripts

### ISSUE THREAD

**Issue by sahandv** [Sydney-Informatics-Hub/aerial-annotation#23]
We need all the scripts to download data in one place. This can be a single folder with multiple scripts for starters, but we can merge them up later.
The following scripts should be merged and pushed to maind in a single directory:

- [ ] downloading sixmaps rasters
- [ ] downloading osm buildings rasters
- [ ] downloading osm annotations with all pre/post processing steps.

We also need to have the tree annotation makers clearly instructed.
