### ISSUE TITLE
Building cleanup

### ISSUE THREAD

**Issue by sahandv** [Sydney-Informatics-Hub/aerial-annotation#27]
- [x] Remove elevators
- [x] recode kiosks to be 1 level
- [x] zeros to 1 level
- [x] 1.5 to 1 level
- [x] remove 7m
- [x] nearest neighbours for null
- [x] new column to have a level category: 1-3  |  4-9  |  10+

Sample running script:
```
python scripts/osm_cleaner.py --osm_path /home/sahand/Data/GIS2COCO/osm_building_annotations_by_10_percent_grid/ --columns /home/sahand/Data/GIS2COCO/osm_columns.csv 
```
