### ISSUE TITLE
ABS Tiling system

### ISSUE THREAD

**Issue by hlydecker** [Sydney-Informatics-Hub/aerial-annotation#7]
## Problem: 
How to split up the aerial imagery tiles intelligently so we won't get weird things?

## Solution: 
Instead of creating arbitrary tiles, we can use ABS boundaries (e.g. SA1). We can cut squares that are the bounding box of each of these and use them as training data.

## Data Sources:

- [ABS SA1 data](https://www.abs.gov.au/statistics/standards/australian-statistical-geography-standard-asgs-edition-3/jul2021-jun2026/main-structure-and-greater-capital-city-statistical-areas/statistical-area-level-1)
- [Open Street Map](https://overpass-turbo.eu/#)
- [NSW Sixmaps WMS](https://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Imagery/MapServer)

## References

- [WMS explainer](https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/#5/109.97/16.94)

## Tasks

- [x] Write a function to trim an aerial image based on the SA1 polygon boundary of a single SA1 zone. 
- [x] Write a function for loading in aerial imagery from NSW SixMaps web map server based on a defined geographic extent. The script should allow us to specify the resolution of the imagery, defined as "zoom" (default to the highest res, 23).
- [x] Write a function to stitch trimmed SA1 images together
- [ ] Write a function to merge polygon data from single SA1 bounds together
- [ ] Write a notebook demonstrating all of these functionalities
- [ ] Write a function for calculating the percentage of an SA1 polygon that is covered by open street map building polygons.
- [x] Identify a threshold for percentage of building cover in which all buildings in an SA1 are annotated.
- [ ] Write a script doing end to end processing with all these steps.
- [ ] Create a dataset of SA1 zones that are completely annotated by OSM and the associated cropped max zoom aerial imagery from sixmaps for each one. Convert this dataset into COCO and upload to roboflow.

## Bonus
- [x] Extract all SA1 boundary polygons + raster sixmaps images for SA1s that have at least one OSM building polygon.
- [ ] Write a script to compare coco polygon predictions vs open street map polygons and calculate the percent overlap
- [ ] Run prediction using the proof of concept building detector.
- [ ] Compare predictions vs the osm data and reject all SA1s where the osm annotated buildings do not include all of the detected buildings.

**Comment by hlydecker** [comment]
I'll be providing a list of SA1s for us to focus on extracting based on some analysis I did via QGIS.
